### ISSUE TITLE
Side by side diffs

### ISSUE THREAD

**Issue by rakanalh** [charignon/greview#3]
Not sure if this one is easy to implement, but i think an interface similar to Github's side-by-side view helps alot for people like myself who like to view the old & new code in a vertical split

**Comment by charignon** [comment]
Have you tried https://github.com/mgalgs/diffview-mode? Essentially the review is a `.diff` file and this should work out of the box.

**Comment by rakanalh** [comment]
Nice! Thank you for that suggestion.

For those looking for the same thing, i've been able to configure it with `scroll-all-mode` as such:
```
(use-package diffview
  :config
  ;; scroll-all-mode doesn't work with mouse.
  ;; WORKAROUND: https://www.emacswiki.org/emacs/ScrollAllMode
  (defun mwheel-scroll-all-function-all (func &optional arg)
    (if (and scroll-all-mode arg)
        (save-selected-window
          (walk-windows
           (lambda (win)
             (select-window win)
             (condition-case nil
                 (funcall func arg)
               (error nil)))))
      (funcall func arg)))

  (defun mwheel-scroll-all-scroll-up-all (&optional arg)
    (mwheel-scroll-all-function-all 'scroll-up arg))

  (defun mwheel-scroll-all-scroll-down-all (&optional arg)
    (mwheel-scroll-all-function-all 'scroll-down arg))

  (setq mwheel-scroll-up-function 'mwheel-scroll-all-scroll-up-all)
  (setq mwheel-scroll-down-function 'mwheel-scroll-all-scroll-down-all)
  ;; Activate scoll-all-mode when in diffview mode
  (add-hook 'diffview-mode (lambda() (scroll-all-mode)))
  )
```

So triggering `M-x diffview-current` in the diff-file should activate diffview mode with scroll-all & mouse support.

**Comment by agzam** [comment]
what about ediff? Is there a similar trick to make it work with ediff? Afaik magit when pressed `e` on a diff, opens ediff buffer at that hunk location, maybe something similar would be possible here as well?
